### ISSUE TITLE
Problems with filenames including a space

### ISSUE THREAD

**Issue by simonstearn1** [pplr/redmine-libsvn#4] opened 2010-03-19 15:46 UTC
This seems to cause problems when checking in a filename including a space.

**Comment by pplr** [comment] 2010-03-20 15:35
I tried to reproduce the bug without success. Here is how I proceeded :
1. I checked out a file named "file with space"
2. Tried "changes", "entry", "annotate" actions related to this commited file

**Comment by panga** [comment] 2010-03-22 12:06
@pplr,

I have the same problem. The problem is that any containing spaces in URL  (directories or files), catches a RailsInvalidUrl exception. Its because the url isn't escaped.

To fix this, alter "target(path)" to "target(URI.escape(path))" in all methods.

Fixed :)

**Comment by pplr** [comment] 2010-03-22 18:40
Escape URL passed to libsvn to avoid Svn::Error::RaIllegalUrl exceptions. closed by 3d8db5623181c31e0734e8124afeb2c87b9f73f4

**Closed as completed by pplr** 2010-03-22 18:40 UTC
