### ISSUE TITLE
Can't navigate in subversion if the address of the repository is not the root

### ISSUE THREAD

**Issue by victornoel** [pplr/redmine-libsvn#2] opened 2010-02-20 14:09 UTC
Hello, I reported this bug at redmine's bugtracker but I think this is from this plugin, you can see the full description there:
http://www.redmine.org/issues/4879

Thanks

**Comment by pplr** [comment] 2010-02-22 19:07
Hello,
I can't reproduce the bug your describing. Can you give me more details on the version of redmine you use ? Can you observe that disabling the libsvn plugin fixes the bug ?

**Comment by victornoel** [comment] 2010-02-23 10:15
Hello,

The people who manage the server are not there currently, so I will come back to you next week when I have more information for you :)

Thank you

**Comment by victornoel** [comment] 2010-03-01 11:12
Hello, finally some answers:
We are using Redmine 0.9.2 and disabling the plugin fixes this bug.

Thank you.

**Comment by panga** [comment] 2010-03-18 17:50
Hi,

I had the same problem but fixed it by changing the method "def entries".
The error was in :name and :path entries.

:name => URI.unescape(path),
:path => ((path_argument.empty? ? "" : "#{path_argument}/") + path),

Where "path_argument" is the "path" given by argument.

**Comment by pplr** [comment] 2010-03-20 15:01
Fix malformed entries path for non root repositories. closed by cecfe06405cf01c2284b1a67beae74c3aa747c83
Fix fetch_changeset exception when tracking a folder created after the
200th revision. closed by cecfe06405cf01c2284b1a67beae74c3aa747c83

**Closed as completed by pplr** 2010-03-20 15:01 UTC

**Comment by pplr** [comment] 2010-03-20 15:03
Thanks for reporting this bug.
